export const bottomGradient = "#005096"; // Deep sea blue
export const middleGradient = "#23A0D5"; // Cerulean
export const topGradient = "#6BD5FF"; // Malibu
export const fontColor = "#1a1a1a";
export const subFontColor = "#a9acb1";
export const lightColor = "#fefbf1";
export const lightColorBox = "#f7f7f8";
export const darkColor = "#1d252a";
export const darkColorBox = "#2c353d";
export const mainColor = "#f04a01";
